### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by leornt** [u1234x1234/youtube-sync#2]
Hey there, could you please add support for ARM64? It should be possible using `buildx`

**Comment by u1234x1234** [comment]
Hi Leonardo,

I've build and pushed linux/arm64 image with `buildx` https://hub.docker.com/layers/youtube-sync/u1234x1234/youtube-sync/1.0.11/images/sha256-8675ec3a7de6f56c248d4d028f004ce2fe02a38a9e762bc8e20f85b56a700eec?context=explore

Could you please check if this solves your problem?

**Comment by leornt** [comment]
It worked like a charm, I'm using a free Oracle Ampere server with Jellyfin and Finamp
As a suggestion, the next build you may release, you can build with multi arch, so we can use in amd64 and arm64
Thank you so much for the fix, excelent project

**Comment by u1234x1234** [comment]
Thank you for the detailed answer!
